//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualMindWebTest.VirtualMindService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseReturn", Namespace="http://schemas.datacontract.org/2004/07/VirtualMindTestService.Returns.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VirtualMindWebTest.VirtualMindService.ReturnOfMoneyVNIoeB4G))]
    public partial class BaseReturn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualMindWebTest.VirtualMindService.Error errorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualMindWebTest.VirtualMindService.Error error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/BE.Models.Base")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                if ((this.codeField.Equals(value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnOfUserVNIoeB4G", Namespace="http://schemas.datacontract.org/2004/07/VirtualMindTestService.Returns")]
    [System.SerializableAttribute()]
    public partial class ReturnOfUserVNIoeB4G : VirtualMindWebTest.VirtualMindService.BaseReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualMindWebTest.VirtualMindService.User itemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualMindWebTest.VirtualMindService.User[] listField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualMindWebTest.VirtualMindService.User item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualMindWebTest.VirtualMindService.User[] list {
            get {
                return this.listField;
            }
            set {
                if ((object.ReferenceEquals(this.listField, value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnOfMoneyVNIoeB4G", Namespace="http://schemas.datacontract.org/2004/07/VirtualMindTestService.Returns")]
    [System.SerializableAttribute()]
    public partial class ReturnOfMoneyVNIoeB4G : VirtualMindWebTest.VirtualMindService.BaseReturn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualMindWebTest.VirtualMindService.Money itemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VirtualMindWebTest.VirtualMindService.Money[] listField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualMindWebTest.VirtualMindService.Money item {
            get {
                return this.itemField;
            }
            set {
                if ((object.ReferenceEquals(this.itemField, value) != true)) {
                    this.itemField = value;
                    this.RaisePropertyChanged("item");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VirtualMindWebTest.VirtualMindService.Money[] list {
            get {
                return this.listField;
            }
            set {
                if ((object.ReferenceEquals(this.listField, value) != true)) {
                    this.listField = value;
                    this.RaisePropertyChanged("list");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Money", Namespace="http://schemas.datacontract.org/2004/07/BE.Models")]
    [System.SerializableAttribute()]
    public partial class Money : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valueToBuyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double valueToSellField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.lastUpdateField, value) != true)) {
                    this.lastUpdateField = value;
                    this.RaisePropertyChanged("lastUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valueToBuy {
            get {
                return this.valueToBuyField;
            }
            set {
                if ((this.valueToBuyField.Equals(value) != true)) {
                    this.valueToBuyField = value;
                    this.RaisePropertyChanged("valueToBuy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double valueToSell {
            get {
                return this.valueToSellField;
            }
            set {
                if ((this.valueToSellField.Equals(value) != true)) {
                    this.valueToSellField = value;
                    this.RaisePropertyChanged("valueToSell");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/BE.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VirtualMindService.IVirtualMindService")]
    public interface IVirtualMindService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtualMindService/Cotizacion", ReplyAction="http://tempuri.org/IVirtualMindService/CotizacionResponse")]
        VirtualMindWebTest.VirtualMindService.ReturnOfMoneyVNIoeB4G Cotizacion(string money);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtualMindService/Usuarios", ReplyAction="http://tempuri.org/IVirtualMindService/UsuariosResponse")]
        VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G Usuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtualMindService/GetUserById", ReplyAction="http://tempuri.org/IVirtualMindService/GetUserByIdResponse")]
        VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtualMindService/InsertUser", ReplyAction="http://tempuri.org/IVirtualMindService/InsertUserResponse")]
        VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G InsertUser(VirtualMindWebTest.VirtualMindService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtualMindService/UpdateUser", ReplyAction="http://tempuri.org/IVirtualMindService/UpdateUserResponse")]
        VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G UpdateUser(VirtualMindWebTest.VirtualMindService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVirtualMindService/DeleteUser", ReplyAction="http://tempuri.org/IVirtualMindService/DeleteUserResponse")]
        VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G DeleteUser(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVirtualMindServiceChannel : VirtualMindWebTest.VirtualMindService.IVirtualMindService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VirtualMindServiceClient : System.ServiceModel.ClientBase<VirtualMindWebTest.VirtualMindService.IVirtualMindService>, VirtualMindWebTest.VirtualMindService.IVirtualMindService {
        
        public VirtualMindServiceClient() {
        }
        
        public VirtualMindServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VirtualMindServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualMindServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VirtualMindServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VirtualMindWebTest.VirtualMindService.ReturnOfMoneyVNIoeB4G Cotizacion(string money) {
            return base.Channel.Cotizacion(money);
        }
        
        public VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G Usuarios() {
            return base.Channel.Usuarios();
        }
        
        public VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G InsertUser(VirtualMindWebTest.VirtualMindService.User user) {
            return base.Channel.InsertUser(user);
        }
        
        public VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G UpdateUser(VirtualMindWebTest.VirtualMindService.User user) {
            return base.Channel.UpdateUser(user);
        }
        
        public VirtualMindWebTest.VirtualMindService.ReturnOfUserVNIoeB4G DeleteUser(int userId) {
            return base.Channel.DeleteUser(userId);
        }
    }
}
